### ISSUE TITLE
The download link doesn't work

### ISSUE THREAD

**Issue by hellohelloriver** [XinyiYing/BasicIRSTD#1]
Hello, thank you for your helpful work.
I find the download link of datasets doesn't work. Could you please provide a new one?
<img width="883" alt="截屏2023-04-25 16 45 19" src="https://user-images.githubusercontent.com/131757041/234224513-183798d9-bbcb-4f3e-b0a8-2491f54f5881.png">
I have another question about the benchmark. What is the used subdivision of each dataset?
On NUAA-SIRST, are they trained on train.txt or trainval.txt?

**Comment by XinyiYing** [comment]
We have updated the download link. In addition, we upload a folder './datasets/' to release the files for data split.

**Comment by hellohelloriver** [comment]
Thx
