### ISSUE TITLE
评测指标的问题

### ISSUE THREAD

**Issue by QYR123** [XinyiYing/BasicIRSTD#10]
你好，请问是否有传统方法的模型工具箱，还有一个问题，评测指标是否可以有precision，recall以及f1。

**Comment by XinyiYing** [comment]
1. 传统方法的模型工具箱
由于授权问题，暂时不会制作传统方法的模型工具箱，可以参照https://github.com/Tianfang-Zhang/awesome-infrared-small-targets 公布的论文自行收集。

2. 评测指标
由于红外小目标检测算法通用指标是检测率，虚警率。
因此目前没有结合precision，recall以及f1到代码当中，您可以自行修改评测指标为precision，recall以及f1进行评测。
