### ISSUE TITLE
ModuleNotFoundError: No module named 'functions'

### ISSUE THREAD

**Issue by Web-AK** [XinyiYing/BasicIRSTD#11]
@XinyiYing 尊敬的作者，你好！
      我在服务器上运行train.py文件时遇到ModuleNotFoundError: No module named 'functions'的问题，尝试了好久不知道如何解决。
      
![image](https://github.com/XinyiYing/BasicIRSTD/assets/60963694/920da78c-d554-4868-b667-c89dd3426cdf)
       看报错，问题出在ISNet模型的DCN可变性卷积，查看ISNet的readme 尝试去安装了DCNv2：
![image](https://github.com/XinyiYing/BasicIRSTD/assets/60963694/0470c6c5-0558-49f0-8957-3cf934811f7e)
       运行testcuda.py:
![image](https://github.com/XinyiYing/BasicIRSTD/assets/60963694/f3081990-f553-44eb-bad0-6a9db83775c5)
![image](https://github.com/XinyiYing/BasicIRSTD/assets/60963694/a6767ccf-02d7-4134-8619-3a95bc5c10cf)
       

再次运行train.py还是报错：ModuleNotFoundError: No module named 'functions'
       期待您的回复！

**Comment by XinyiYing** [comment]
![image](https://github.com/XinyiYing/BasicIRSTD/assets/35837640/638fdd01-d6b1-42a3-8ae1-6170df5e5180)
运行bash.sh后，得到的文件如图所示，应该是有functions这个文件夹存在的。
如果你那边也能看到这个文件夹的生成，可能是两个问题导致的上述报错
（1）引用functions这个包的路径需要修改。需要将“from functions.deform_conv_func”改成“from ..functions.deform_conv_func”或者"from model.ISNet.DCNv2.DCN.functions.deform_conv_func"，我不确定你打开project的根目录是什么，各种路径方式都可以试试。
（2）当前conda环境中已有DCNv1,导致包重复引用没有覆盖。需要找到./anaconda3/envs/xxx/lib/python3.7/site-packages/DCN-1.0-py3.7-linux-x86_64.egg，DCNV2.egg-link这两个文件删掉，然后重新编译DCN。

**Comment by Web-AK** [comment]
> @XinyiYing 尊敬的作者，你好！ 我在服务器上运行train.py文件时遇到ModuleNotFoundError: No module named 'functions'的问题，尝试了好久不知道如何解决。
> 
> ![image](https://private-user-images.githubusercontent.com/60963694/284517202-920da78c-d554-4868-b667-c89dd3426cdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNDY4MTcsIm5iZiI6MTcwMTE0NjUxNywicGF0aCI6Ii82MDk2MzY5NC8yODQ1MTcyMDItOTIwZGE3OGMtZDU1NC00ODY4LWI2NjctYzg5ZGQzNDI2Y2RmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDA0NDE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1ZDhhZGE1MjMzMThjMTdjMWIwMTNlMTZjNWVhMzJmYzIxMWMxMzkzNTQ5ZTg1YzhjYWU1YzM5NmZlMDYzMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.paIY4osdgfV2zjRMHtKIIqyA2QT-Azfqvw4GNLmRsJU) 看报错，问题出在ISNet模型的DCN可变性卷积，查看ISNet的readme 尝试去安装了DCNv2： ![image](https://private-user-images.githubusercontent.com/60963694/284517704-0470c6c5-0558-49f0-8957-3cf934811f7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNDY4MTcsIm5iZiI6MTcwMTE0NjUxNywicGF0aCI6Ii82MDk2MzY5NC8yODQ1MTc3MDQtMDQ3MGM2YzUtMDU1OC00OWYwLTg5NTctM2NmOTM0ODExZjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDA0NDE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzM2MxY2I0YWU3MTkwODI3OTA3MzU3YTY5NzJmNjc0YTRmYmU5NjA5NzdmMDZjMTU3NGE5ZjE3NGIxNDVjNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yHQABsyqR4NkWBgDE72uYJOHu3wKZtv6ut3COVCZtHw) 运行testcuda.py: ![image](https://private-user-images.githubusercontent.com/60963694/284520861-f3081990-f553-44eb-bad0-6a9db83775c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNDY4MTcsIm5iZiI6MTcwMTE0NjUxNywicGF0aCI6Ii82MDk2MzY5NC8yODQ1MjA4NjEtZjMwODE5OTAtZjU1My00NGViLWJhZDAtNmE5ZGI4Mzc3NWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDA0NDE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5OTVjNDgxOGMzYWVhZDU4YThkM2E2MjQ1OGI0NmFiYmJhOGQyNmIwNzQ3NjE2YmY1ODlhZGZlZmM3N2ZlNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x1yOKkoxHX_mbn6tC90d9aXo17GB628aNJKQ-OGr99Y) ![image](https://private-user-images.githubusercontent.com/60963694/284519578-a6767ccf-02d7-4134-8619-3a95bc5c10cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNDY4MTcsIm5iZiI6MTcwMTE0NjUxNywicGF0aCI6Ii82MDk2MzY5NC8yODQ1MTk1NzgtYTY3NjdjY2YtMDJkNy00MTM0LTg2MTktM2E5NWJjNWMxMGNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDA0NDE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwYTI0YmM3NzNiYjNmNTFiNTc5ZjdhZjMwMGI0ZTQ2MWVkNWNiNmUxYjkzODYxNDAyZThkMmY5MTY4NjE0OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pZb-MVSb41GY5Z_mJfb9GujvyOkelJiNhVVjQ-hSzXY)
> 
> 再次运行train.py还是报错：ModuleNotFoundError: No module named 'functions' 期待您的回复！

**Comment by fengjingchehu** [comment]
i wonder how did you solve it?
