### ISSUE TITLE
评测指标Fa的计算问题

### ISSUE THREAD

**Issue by yeah-creater** [XinyiYing/BasicIRSTD#12]
metircs.py的 line 72 : self.dismatch = [x for x in self.image_area_total if x not in self.image_area_match] 对于某些数据结果好像就不太对了。

**Comment by yeah-creater** [comment]
例如极端情况下： self.image_area_total = [np.array(2.0), np.array(2.0), np.array(2.0)] ,而 self.image_area_match = [np.array(2.0)], 若根据上述代码，最终结果是 [ ], 而实际结果需要是  [np.array(2.0), np.array(2.0)] 。上下文没有读透，若有错误，还请谅解。

**Comment by XinyiYing** [comment]
抱歉回复晚了，我的github一直登不上。关于Fa的计算问题已经修复，详细见代码metircs.py。readme.md和log中的test的值已经更新。
