### ISSUE TITLE
试过在 NUDT-SIRST-Sea 上训练得到的结果吗，第一个epoch之后miou等全是0

### ISSUE THREAD

**Issue by Deaddawn** [XinyiYing/BasicIRSTD#19]
能帮忙看看这个问题吗

**Comment by wideirstd** [comment]
训练过没有问题，耐心等待多几个epoch，总epoch数量是400.

**Comment by XinyiYing** [comment]
在 NUDT-SIRST-Sea 上训练过没有问题，可以多等几个epoch，总共是400epoch.

**Comment by Deaddawn** [comment]
> 在 NUDT-SIRST-Sea 上训练过没有问题，可以多等几个epoch，总共是400epoch.

方便说一下setting吗，网络用的是？

**Comment by Deaddawn** [comment]
训完了，还是0

**Comment by Deaddawn** [comment]
方便给一下实验setting吗，是用的哪些网络，我这里基本都试过了，这个数据集中存在很多全黑的mask，应该是有影响的



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月25日 10:31 |
| 收件人 | ***@***.***> |
| 抄送至 | ZD ***@***.***>***@***.***> |
| 主题 | Re: [XinyiYing/BasicIRSTD] 试过在 NUDT-SIRST-Sea 上训练得到的结果吗，第一个epoch之后miou等全是0 (Issue #19) |

训练过没有问题，耐心等待多几个epoch，总epoch数量是400.

**Comment by XinyiYing** [comment]
setting都维持不动的，这个是训练过程记录。
![image](https://github.com/XinyiYing/BasicIRSTD/assets/35837640/61b14805-7fef-4044-b21e-77f488cee1c0)

**Comment by Deaddawn** [comment]
> setting都维持不动的，这个是训练过程记录。 ![image](https://private-user-images.githubusercontent.com/35837640/334105153-61b14805-7fef-4044-b21e-77f488cee1c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4Njk5NDYsIm5iZiI6MTcxNjg2OTY0NiwicGF0aCI6Ii8zNTgzNzY0MC8zMzQxMDUxNTMtNjFiMTQ4MDUtN2ZlZi00MDQ0LWIyMWUtNzdmNDg4Y2VlMWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDA0MTQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlNzhkNjkxYTRmZDJmZWI4M2Q5N2EyMzc5ZGNmMzZlNjg4OWNiZTFlYzA3ZWNhM2FhMmU5NzA1NTlmODk0NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5IqP4iX8NqfH5ZbIeH_ehN32jSN7jQE4hVmjEWaMyzE)

感谢，请问用的是哪个backbone？

**Comment by XinyiYing24** [comment]
DNANet，公布得每个backbone都有结果，但是精度不高。

**Comment by XinyiYing** [comment]
train里面得所有backbone都能正常运行出结果。

**Comment by Deaddawn** [comment]
ok，感谢回复。



---- 回复的原邮件 ----
| 发件人 | Xinyi ***@***.***> |
| 日期 | 2024年05月29日 09:54 |
| 收件人 | ***@***.***> |
| 抄送至 | ZD ***@***.***>***@***.***> |
| 主题 | Re: [XinyiYing/BasicIRSTD] 试过在 NUDT-SIRST-Sea 上训练得到的结果吗，第一个epoch之后miou等全是0 (Issue #19) |

train里面得所有backbone都能正常运行出结果。

**Comment by Jupiter-Wang** [comment]
作者您好，我的训练过程记录和您图片中的一样，但您有注意到每轮测试出来的pixAcc，mIoU都很低吗，并且测试的结果这两个指标也很低，请问这是正常的吗
