### ISSUE TITLE
train之后不训练，一直卡着不动

### ISSUE THREAD

**Issue by MantianxingLYJ** [XinyiYing/BasicIRSTD#25]
运行之后只显示如下然后就卡着不动了，没有训练，也没有报错

icpr_dataset    UIUNet
icpr_dataset    {'mean': 76.04834747314453, 'std': 28.732160568237305}

**Comment by MOCUISHLE-AC** [comment]
我也遇到了相同的问题，请问您解决了吗

**Comment by XinyiYing** [comment]
一般训练开始卡着不动是因为没有检索到数据集的均值方差所以重新算比较花时间。代码中默认的数据集及其均值方差见utils.py 94-105行（如下）。
![image](https://github.com/XinyiYing/BasicIRSTD/assets/35837640/da7a91c1-e929-4051-8502-aa7a027277cc)
为方便使用，训练代码train.py 18行中给定了一个参数img_norm_cfg，类型是dict，可以自行设置均值方差，检索到后就会直接使用不用再重新计算。
注意：由于命令行无法对dict进行传参。因此，如果需要使用img_norm_cfg设置均值方差，直接改train.py后运行。
此外，train.py 20-22行额外提供了img_norm_cfg_mean和img_norm_cfg_std两个float参数，可以直接通过命令行传参。python train.py --model_names ACM ALCNet --dataset_names NUAA-SIRST --img_norm_cfg_mean 76.04834747314453 --img_norm_cfg_std 28.732160568237305
运行命令可以参考PRCV 2024 WideIRSTD挑战赛的代码提交示例 [https://bohrium.dp.tech/notebooks/21145676824](https://bohrium.dp.tech/notebooks/21145676824)

**Comment by XinyiYing** [comment]
相关问题已经在[issue20](https://github.com/XinyiYing/BasicIRSTD/issues/20)做出说明

**Comment by MOCUISHLE-AC** [comment]
谢谢您的回复，十分感谢您提供的codebase，我发现卡着不动的原因可能是，random_crop 进入了死循环，因为有些图片中根本就没有小目标（例如NUAA v2中一些图片），我觉得可以通过设置 pos_prob=None 解决，是不是这样呢？万分感谢
![image](https://github.com/XinyiYing/BasicIRSTD/assets/80635928/035f448d-9228-4ab4-98b8-f6f9c6cd7796)

**Comment by MOCUISHLE-AC** [comment]
十分感谢您的回答，现在懂了这个random_crop 的设计含义了，太感谢了。祝您论文多多，学术长青！

**Comment by XinyiYing** [comment]
没事儿，不用客气，也祝您学业有成，前程似锦！
