### ISSUE TITLE
NUDT 数据集上DNANet 结果和  LESPS、DNANet原文差距

### ISSUE THREAD

**Issue by MOCUISHLE-AC** [XinyiYing/BasicIRSTD#27]
作者您好，我也关注了您LESPS的工作。
我发现您在LESPS，同样跑了NUDT（DNANet），mIoU = 87.42，接近原始DNANet 87.09
![image](https://github.com/user-attachments/assets/5576f7b6-69cb-4413-9dc7-c1a4e699625e)
现在您的框架可以达到90+，想知道采取了哪些优化，谢谢。

PS：对比了一下LESPS，感觉两版差别不大

**Comment by XinyiYing** [comment]
BasicIRSTD和LESPS差异：
1）框架不同。BasicIRSTD是全监督框架，LESPS是点监督框架。
2）loss不同。BasicIRSTD采用iou loss，LESPS 采用focal loss。由于iou loss会导致点监督框架不收敛，且点监督下正负样本存在极度不平衡问题，所以采用focal loss进行监督。
3）BasicIRSTD框架经过多次优化。大致如下：random crop设计了参数以控制正负样本比例，固定了随机种子为42以确保训练复现性，之前有人提出false alarm计算有问题更新了一下。

**Comment by MOCUISHLE-AC** [comment]
谢谢您的解答，十分感谢
