### ISSUE TITLE
您好，我在使用test和inference时遇到了一些问题

### ISSUE THREAD

**Issue by jzw0707** [XinyiYing/BasicIRSTD#28]
<img width="812" alt="Screenshot 2024-09-24 160333" src="https://github.com/user-attachments/assets/5d9b64e8-ba60-45e6-942e-8b6262e5d99b">
我在做测试的时候遇到了错误, 将dataset_name中的数据集名称替换为.的问题，这是我的命令行参数设置
<img width="954" alt="Screenshot 2024-09-24 160601" src="https://github.com/user-attachments/assets/a8c21b69-efa8-4ae3-8a74-c604f553a11d">

**Comment by XinyiYing** [comment]
pth_dirs参数中“NUDT-SIRST_DNANet”替换为“NUDT-SIRST”即可，代码会识别数据集名称，没有找到NUDT-SIRST_DNANet数据集所以报错
