### ISSUE TITLE
多卡训练

### ISSUE THREAD

**Issue by QYR123** [XinyiYing/BasicIRSTD#29]
你好，怎么进行多卡训练

**Comment by XinyiYing** [comment]
终端运行以下命令：
CUDA_VISIBLE_DEVICES=0,1 python train.py

**Comment by QYR123** [comment]
运行了还是单卡训练

**Comment by XinyiYing** [comment]
下面这句话指示了多卡训练，
![1727922051944](https://github.com/user-attachments/assets/97cfbd9a-2f68-46d1-8740-dfce76acfa14)
我试了我这边可以多卡训练，可能因为model占的显存太小看不出来，可以加大batch size再训练看看不同显卡的显存占用。命令``CUDA_VISIBLE_DEVICES=0,1 python train.py``中的``0,1``指示的是使用的GPU的号码。
