### ISSUE TITLE
请问代码中的SIRST4数据集是哪一个呢？

### ISSUE THREAD

**Issue by Raindow** [XinyiYing/BasicIRSTD#3]
如题

**Comment by XinyiYing** [comment]
由于NUAA-SIRST,NUDT-SIRST,IRSTD-1K三个数据集的图像灰度均值标准差（灰度分布）比较接近，因此将三个数据集整合到一起得到SIRST3数据集。
训练集1676张图，测试集1079张图。
目前没有SIRST4的数据。

**Comment by Raindow** [comment]
好的，谢谢

**Comment by Raindow** [comment]
NUST-SIRST这个数据集的处理是不是在进行中

**Comment by XinyiYing** [comment]
NUST-SIRST数据集标注质量比较差，因此不考虑在这个上面进行训练和评测。
