### ISSUE TITLE
传统方法的IoU、PD、FA是如何计算的？

### ISSUE THREAD

**Issue by Drinkwaterever** [XinyiYing/BasicIRSTD#5]
您好，非常感谢您在红外小目标检测领域的工作付出，这个工具库能开源真的太棒了。
我想请问下，您在不同数据集上进行传统方法的训练时，IoU、PD、FA这几个指标是如何得到的呢？因为我看传统方法的相关论文，它们都是比较SCRG、BSF等指标，没有涉及到上述几个指标。
期望得到您的回复，谢谢！

**Comment by XinyiYing** [comment]
我们提供了基于已有分割结果的评测代码，详情见readme.md中的“Commands for Evaluate on your own results”节。
