### ISSUE TITLE
/model/model/ISNet/DCNv2 编译问题

### ISSUE THREAD

**Issue by dudiaoxifenglie** [XinyiYing/BasicIRSTD#6]
您好，非常感谢您的工作。但在使用过程中，发现了一些问题，希望能够予以解答。在按照model/ISNet/DCNv2/README.md的提示，运行"python3 setup.py build develop"时，报错如下：
unning build
running build_ext
building '_ext' extension
creating /home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/build
creating /home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/build/temp.linux-x86_64-cpython-38
creating /home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/build/temp.linux-x86_64-cpython-38/home
creating /home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/build/temp.linux-x86_64-cpython-38/home/fgd
creating /home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/build/temp.linux-x86_64-cpython-38/home/fgd/Code
creating /home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/build/temp.linux-x86_64-cpython-38/home/fgd/Code/Infrared Small-Target  Algorithms
creating /home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/build/temp.linux-x86_64-cpython-38/home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning
creating /home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/build/temp.linux-x86_64-cpython-38/home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main
creating /home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/build/temp.linux-x86_64-cpython-38/home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model
creating /home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/build/temp.linux-x86_64-cpython-38/home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet
creating /home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/build/temp.linux-x86_64-cpython-38/home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2
creating /home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/build/temp.linux-x86_64-cpython-38/home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/src
creating /home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/build/temp.linux-x86_64-cpython-38/home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/src/cpu
creating /home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/build/temp.linux-x86_64-cpython-38/home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/src/cuda
Emitting ninja build file /home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/build/temp.linux-x86_64-cpython-38/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.10.0
creating build/lib.linux-x86_64-cpython-38
g++ -pthread -B /home/fgd/SOFT/anaconda3/envs/Pytracking/compiler_compat -Wl,--sysroot=/ -pthread -shared -B /home/fgd/SOFT/anaconda3/envs/Pytracking/compiler_compat -L/home/fgd/SOFT/anaconda3/envs/Pytracking/lib -Wl,-rpath=/home/fgd/SOFT/anaconda3/envs/Pytracking/lib -Wl,--no-as-needed -Wl,--sysroot=/ "/home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/build/temp.linux-x86_64-cpython-38/home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/src/cpu/dcn_v2_cpu.o" "/home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/build/temp.linux-x86_64-cpython-38/home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/src/cpu/dcn_v2_im2col_cpu.o" "/home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/build/temp.linux-x86_64-cpython-38/home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/src/cpu/dcn_v2_psroi_pooling_cpu.o" "/home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/build/temp.linux-x86_64-cpython-38/home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/src/cuda/dcn_v2_cuda.o" "/home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/build/temp.linux-x86_64-cpython-38/home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/src/cuda/dcn_v2_im2col_cuda.o" "/home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/build/temp.linux-x86_64-cpython-38/home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/src/cuda/dcn_v2_psroi_pooling_cuda.o" "/home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/build/temp.linux-x86_64-cpython-38/home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/src/vision.o" -L/home/fgd/SOFT/anaconda3/envs/Pytracking/lib/python3.8/site-packages/torch/lib -L/usr/local/cuda-11.3/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda_cu -ltorch_cuda_cpp -o build/lib.linux-x86_64-cpython-38/_ext.cpython-38-x86_64-linux-gnu.so
g++: error: /home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/build/temp.linux-x86_64-cpython-38/home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/src/cpu/dcn_v2_cpu.o: 没有那个文件或目录
g++: error: /home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/build/temp.linux-x86_64-cpython-38/home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/src/cpu/dcn_v2_im2col_cpu.o: 没有那个文件或目录
g++: error: /home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/build/temp.linux-x86_64-cpython-38/home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/src/cpu/dcn_v2_psroi_pooling_cpu.o: 没有那个文件或目录
g++: error: /home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/build/temp.linux-x86_64-cpython-38/home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/src/cuda/dcn_v2_cuda.o: 没有那个文件或目录
g++: error: /home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/build/temp.linux-x86_64-cpython-38/home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/src/cuda/dcn_v2_im2col_cuda.o: 没有那个文件或目录
g++: error: /home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/build/temp.linux-x86_64-cpython-38/home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/src/cuda/dcn_v2_psroi_pooling_cuda.o: 没有那个文件或目录
g++: error: /home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/build/temp.linux-x86_64-cpython-38/home/fgd/Code/Infrared Small-Target  Algorithms/DeepLearning/BasicIRSTD-main/model/ISNet/DCNv2/src/vision.o: 没有那个文件或目录

**Comment by XinyiYing** [comment]
建议使用ubuntu系统完成DCN的编译，windows环境下需要安装Visual Studio，通过python调用Visual Studio编译c和cuda文件，经常会存在环境问题导致的编译失败，调试困难。
