### ISSUE TITLE
NUDT-SIRST-Sea 

### ISSUE THREAD

**Issue by Linaom1214** [XinyiYing/BasicIRSTD#7]
您好，有NUDT-SIRST-Sea这个数据集的测试结果吗？

**Comment by XinyiYing** [comment]
深度学习方法已经训练评测完成，传统算法评测还需要一段时间，请耐心等待

**Comment by Linaom1214** [comment]
> 深度学习方法已经训练评测完成，传统算法评测还需要一段时间，请耐心等待。 由于传统算法中有一些算法跑得很慢，如果有跑出结果的同学也可以把结果发给我评测，我们一起维护这个repo，感谢大家的支持！

您好，我还没看到这个数据集相关的测试结果。

**Comment by Springder** [comment]
> 深度学习方法已经训练评测完成，传统算法评测还需要一段时间，请耐心等待。 由于传统算法中有一些算法跑得很慢，如果有跑出结果的同学也可以把结果发给我评测，我们一起维护这个repo，感谢大家的支持！

您好！我看您已经把深度学习方法集成进来了。咱可以把传统方法代码也集成进来吗？虽然网上有各种各样的代码，但是不同版本不同参数跑出来的结果可能有差异。

**Comment by Linaom1214** [comment]
> > 深度学习方法已经训练评测完成，传统算法评测还需要一段时间，请耐心等待。 由于传统算法中有一些算法跑得很慢，如果有跑出结果的同学也可以把结果发给我评测，我们一起维护这个repo，感谢大家的支持！
> 
> 您好！我看您已经把深度学习方法集成进来了。咱可以把传统方法代码也集成进来吗？虽然网上有各种各样的代码，但是不同版本不同参数跑出来的结果可能有差异。

@Springder  您可以关注一下我们这个开源项目 https://github.com/Linaom1214/ISTD-Benchmark.git

**Comment by Springder** [comment]
> > > 深度学习方法已经训练评测完成，传统算法评测还需要一段时间，请耐心等待。 由于传统算法中有一些算法跑得很慢，如果有跑出结果的同学也可以把结果发给我评测，我们一起维护这个repo，感谢大家的支持！
> > 
> > 
> > 您好！我看您已经把深度学习方法集成进来了。咱可以把传统方法代码也集成进来吗？虽然网上有各种各样的代码，但是不同版本不同参数跑出来的结果可能有差异。
> 
> @Springder 您可以关注一下我们这个开源项目 https://github.com/Linaom1214/ISTD-Benchmark.git
Get it!
