### ISSUE TITLE
DNA的NUDT数据集指标

### ISSUE THREAD

**Issue by YuanMortal** [XinyiYing/BasicIRSTD#8]
为什么DNANet原论文的IoU只有87，您提供的这个框架跑出来的结果是94呢？为什么会有这么大的差距

**Comment by XinyiYing** [comment]
DNANet和BasicIRSTD使用的算法代码框架不一样，训练和评测方便都有些微差距。具体可以见代码部分。

训练主要是优化器，训练策略，是否resize图像和标签，图像增强策略等等都有所差异。

评测差距应该不大，你可以试试把DNANet算法代码框架下训练的模型放在BasicIRSTD下进行评测，看看是模型的问题还是评测代码的差异。

NUDT数据集主要采用的是仿真数据，去仔细看数据的话很明显可以看出目标类型比较单一，模型去拟合比较容易，按理检测性能应该就是比较高的。你可以进一步探索。

**Comment by YuanMortal** [comment]
好的，感谢
